version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install MPI
          command: |
            apt update
            apt install -y libopenmpi-dev libclang-dev clang libffi-dev
      - run:
          name: Day1
          command: |
            cd day1
            cargo build --release
            mpirun --allow-run-as-root -np 4 ./target/release/hello
            mpirun --allow-run-as-root -np 4 ./target/release/rank

workflows:
  version: 2
  tests:
    jobs:
      - test
